### ISSUE TITLE
I have 2 commodore 64 that don't work : Request for help

### ISSUE THREAD

**Issue by BensafiM** [shazz/Reparations-de-Commodore#1]
I have 2 commodore 64 that don't work : Request for help.

**Comment by shazz** [comment]
Tell me more :)
What are the symptoms ?

Reminder: NEVER test a C64 with a non checked power supply, If it supplies more than 5.3V DC it will fry your C64 (a bit more) and that's 80% of the  causes...

**Comment by shazz** [comment]
I guess you found the issues..
